### ISSUE TITLE
Migrate Cucumber from JUnit 4 to JUnit 5

### ISSUE THREAD

**Issue by yeikel** [cucumber/cucumber-jvm-migration#4]
### 🤔 What's the problem you're trying to solve?

Migrate existing projects from JUnit4 to JUnit5

### ✨ What's your proposed solution?

Implement a recipe to migrate existing projects using JUnit 4 to JUnit 5

### ⛏ Have you considered any alternatives or workarounds?

The only workaround is to implement this migration manually

### 📚 Any additional context?

https://github.com/cucumber/cucumber-jvm/issues/1149#issuecomment-611716745
https://github.com/cucumber/cucumber-jvm/pull/2362

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by timtebeek** [comment]
Continued here: https://github.com/openrewrite/rewrite-cucumber-jvm/issues/1
