### ISSUE TITLE
Make the first release

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm-migration#5]
### 🤔 What's the problem you've observed?

Setup:
 - [ ] Github release Environment
 - [ ] CHANGELOG.md
 - [ ] Branch protection rules

**Comment by timtebeek** [comment]
After some discussion we've agreed to continue development over on https://github.com/openrewrite/rewrite-cucumber-jvm, such that we tie the release cadence to OpenRewrite releases to pick up any required changes there.
